[custom]
; 不要随意改变关键字，否则会导致出错
; ClashTemplate_Gitee 远程规则 - 在线更新版

; 去广告：支持
; 自动测速：支持
; 微软分流：不支持
; 苹果分流：不支持
; 增强中国IP段：支持
; 增强国外GFW：支持

; 规则集定义
ruleset=🎯 本地直连,https://gh-proxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Lan/Lan.yaml
ruleset=🛑 全球拦截,https://gh-proxy.com/https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/reject.txt
ruleset=🌍 全球代理,https://gh-proxy.com/https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/proxy.txt
ruleset=🎯 本地直连,https://gh-proxy.com/https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/direct.txt
ruleset=🎯 本地直连,https://gh-proxy.com/https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/private.txt
ruleset=🌍 全球代理,https://gh-proxy.com/https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/gfw.txt
ruleset=🌍 全球代理,https://gh-proxy.com/https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/greatfire.txt
ruleset=🌍 全球代理,https://gh-proxy.com/https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/tld-not-cn.txt
ruleset=📲 Telegram,https://gh-proxy.com/https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/telegramcidr.txt
ruleset=🎯 本地直连,https://gh-proxy.com/https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/applications.txt
ruleset=🎬 Disney,https://gh-proxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Disney/Disney.yaml
ruleset=🎬 Netflix,https://gh-proxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Netflix/Netflix.yaml
ruleset=🎬 YouTube,https://gh-proxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/YouTube/YouTube.yaml
ruleset=🎬 HBO,https://gh-proxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/HBO/HBO.yaml
ruleset=🤖 OpenAI,https://gh-proxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/OpenAI/OpenAI.yaml
ruleset=🤖 ClaudeAI,https://gh-proxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Claude/Cl_ude.yaml
ruleset=🔍 Bing,https://gh-proxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Bing/Bing.yaml
ruleset=🔍 Google,https://gh-proxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Google/Google.yaml
ruleset=💻 GitHub,https://gh-proxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/GitHub/GitHub.yaml
ruleset=🎵 Spotify,https://gh-proxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Spotify/Spotify.yaml
ruleset=🎯 本地直连,https://gh-proxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/ChinaMax/ChinaMax_Domain.yaml
ruleset=🎯 本地直连,https://gh-proxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/ChinaMax/ChinaMax_IP_No_IPv6.yaml
ruleset=🎯 本地直连,[]GEOIP,CN
ruleset=🐟 漏网之鱼,[]FINAL

; 代理组定义
custom_proxy_group=🚀 手动切换`select`[]DIRECT`[]♻️ 自动选择`.* icon=https://gitee.com/YoungYannick/Repository/raw/master/images/main/Cool/Cool-500.png
custom_proxy_group=♻️ 自动选择`url-test`.*`https://www.gstatic.com/generate_204`36000 icon=https://gitee.com/YoungYannick/Repository/raw/master/images/icons/Color/Auto.png
custom_proxy_group=🌍 全球代理`select`[]🚀 手动切换`[]♻️ 自动选择`[]DIRECT`.* icon=https://gitee.com/YoungYannick/Repository/raw/master/images/icons/Color/Area.png
custom_proxy_group=🎬 流媒体`select`[]🚀 手动切换`[]♻️ 自动选择`[]DIRECT`.* icon=https://gitee.com/YoungYannick/Repository/raw/master/images/icons/Color/Media.png
custom_proxy_group=🔐 DNS_Proxy`select`[]🚀 手动切换`[]♻️ 自动选择`[]DIRECT`.* icon=https://gitee.com/YoungYannick/Repository/raw/master/images/icons/Color/DNS2.png
custom_proxy_group=📲 Telegram`select`[]🚀 手动切换`[]♻️ 自动选择`[]DIRECT`.* icon=https://gitee.com/YoungYannick/Repository/raw/master/images/icons/Color/Telegram.png
custom_proxy_group=🔍 Google`select`[]🚀 手动切换`[]♻️ 自动选择`[]DIRECT`.* icon=https://gitee.com/YoungYannick/Repository/raw/master/images/icons/Color/Google_Search.png
custom_proxy_group=🎬 YouTube`select`[]🚀 手动切换`[]♻️ 自动选择`[]DIRECT`.* icon=https://gitee.com/YoungYannick/Repository/raw/master/images/icons/Color/YouTube.png
custom_proxy_group=🎬 Netflix`select`[]🎬 流媒体`[]🚀 手动切换`[]♻️ 自动选择`.* icon=https://gitee.com/YoungYannick/Repository/raw/master/images/icons/Color/Netflix.png
custom_proxy_group=🎵 Spotify`select`[]🎬 流媒体`[]🚀 手动切换`[]♻️ 自动选择`[]DIRECT`.* icon=https://gitee.com/YoungYannick/Repository/raw/master/images/icons/Color/Spotify.png
custom_proxy_group=🎬 HBO`select`[]🎬 流媒体`[]🚀 手动切换`[]♻️ 自动选择`.* icon=https://gitee.com/YoungYannick/Repository/raw/master/images/icons/Color/HBO_Max.png
custom_proxy_group=🔍 Bing`select`[]🚀 手动切换`[]♻️ 自动选择`[]DIRECT`.* icon=https://gitee.com/YoungYannick/Repository/raw/master/images/icons/Color/bing.png
custom_proxy_group=🤖 OpenAI`select`[]🚀 手动切换`[]♻️ 自动选择`[]DIRECT`.* icon=https://gitee.com/YoungYannick/Repository/raw/master/images/icons/Color/ChatGPT.png
custom_proxy_group=🤖 ClaudeAI`select`[]🚀 手动切换`[]♻️ 自动选择`[]DIRECT`.* icon=https://gitee.com/YoungYannick/Repository/raw/master/images/icons/Color/claude-ai-icon.png
custom_proxy_group=🎬 Disney`select`[]🎬 流媒体`[]🚀 手动切换`[]♻️ 自动选择`.* icon=https://gitee.com/YoungYannick/Repository/raw/master/images/icons/Color/Disney.png
custom_proxy_group=💻 GitHub`select`[]🚀 手动切换`[]♻️ 自动选择`[]DIRECT`.* icon=https://gitee.com/YoungYannick/Repository/raw/master/images/icons/Color/GitHub.png
custom_proxy_group=🎥 国内媒体`select`[]DIRECT`[]🚀 手动切换`[]♻️ 自动选择`.* icon=https://gitee.com/YoungYannick/Repository/raw/master/images/icons/Color/bilibili_3.png
custom_proxy_group=🎯 本地直连`select`[]DIRECT`[]🚀 手动切换`[]♻️ 自动选择`.* icon=https://gitee.com/YoungYannick/Repository/raw/master/images/icons/Color/Direct.png
custom_proxy_group=🐟 漏网之鱼`select`[]🚀 手动切换`[]♻️ 自动选择`[]DIRECT`.* icon=https://gitee.com/YoungYannick/Repository/raw/master/images/icons/Color/Filter.png

enable_rule_generator=true
overwrite_original_rules=true